// Generated by gencpp from file robosat_gazebo_ros_plugins_msgs/GetModelProperties.msg
// DO NOT EDIT!


#ifndef ROBOSAT_GAZEBO_ROS_PLUGINS_MSGS_MESSAGE_GETMODELPROPERTIES_H
#define ROBOSAT_GAZEBO_ROS_PLUGINS_MSGS_MESSAGE_GETMODELPROPERTIES_H

#include <ros/service_traits.h>


#include <robosat_gazebo_ros_plugins_msgs/GetModelPropertiesRequest.h>
#include <robosat_gazebo_ros_plugins_msgs/GetModelPropertiesResponse.h>


namespace robosat_gazebo_ros_plugins_msgs
{

struct GetModelProperties
{

typedef GetModelPropertiesRequest Request;
typedef GetModelPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetModelProperties
} // namespace robosat_gazebo_ros_plugins_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties > {
  static const char* value()
  {
    return "8f2ac94008b559adc87f7d99565ba995";
  }

  static const char* value(const ::robosat_gazebo_ros_plugins_msgs::GetModelProperties&) { return value(); }
};

template<>
struct DataType< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties > {
  static const char* value()
  {
    return "robosat_gazebo_ros_plugins_msgs/GetModelProperties";
  }

  static const char* value(const ::robosat_gazebo_ros_plugins_msgs::GetModelProperties&) { return value(); }
};


// service_traits::MD5Sum< ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesRequest> should match
// service_traits::MD5Sum< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties >
template<>
struct MD5Sum< ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties >::value();
  }
  static const char* value(const ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesRequest> should match
// service_traits::DataType< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties >
template<>
struct DataType< ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties >::value();
  }
  static const char* value(const ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesResponse> should match
// service_traits::MD5Sum< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties >
template<>
struct MD5Sum< ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties >::value();
  }
  static const char* value(const ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesResponse> should match
// service_traits::DataType< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties >
template<>
struct DataType< ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::robosat_gazebo_ros_plugins_msgs::GetModelProperties >::value();
  }
  static const char* value(const ::robosat_gazebo_ros_plugins_msgs::GetModelPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSAT_GAZEBO_ROS_PLUGINS_MSGS_MESSAGE_GETMODELPROPERTIES_H
